try:
    a=1/0
    print(a)
except:
    print("error")

print("after except")